# This tells Netlify how to build your site
[build]
  command = "node fetch-youtube.js"
  publish = "public"

# This adds the special "Access-Control-Allow-Origin" header
[[headers]]
  for = "/youtube-data.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
